# Birds CUB dataset
birds_images_path: '/Users/rajibdas/Workspace/UB/CV/data/CUB_200_2011/CUB_200_2011/images'
birds_embedding_path: '/Users/rajibdas/Workspace/UB/CV/data/cub_icml'
birds_text_path: '/Users/rajibdas/Workspace/UB/CV/data/cvpr2016_cub/text_c10'
birds_dataset_path: '/Users/rajibdas/Workspace/UB/CV/Text-to-Image-Synthesis/birds.hdf5'
val_split_path: '/Users/rajibdas/Workspace/UB/CV/data/cvpr2016_cub/valclasses.txt'
train_split_path: '/Users/rajibdas/Workspace/UB/CV/data/cvpr2016_cub/trainclasses.txt'
test_split_path: '/Users/rajibdas/Workspace/UB/CV/data/cvpr2016_cub/testclasses.txt'


# flowers dataset
flowers_images_path: '/Users/rajibdas/Workspace/UB/CV/data/flowers_icml'
flowers_embedding_path: '/Users/rajibdas/Workspace/UB/CV/data/flowers_icml'
flowers_text_path: '/Users/rajibdas/Workspace/UB/CV/data/cvpr2016_flowers/text_c10'
flowers_dataset_path: '/Users/rajibdas/Workspace/UB/CV/Text-to-Image-Synthesis/flowers.hdf5'

flowers_val_split_path: '/Users/rajibdas/Workspace/UB/CV/data/cvpr2016_flowers/valclasses.txt'
flowers_train_split_path: '/Users/rajibdas/Workspace/UB/CV/data/cvpr2016_flowers/trainclasses.txt'
flowers_test_split_path: '/Users/rajibdas/Workspace/UB/CV/data/cvpr2016_flowers/testclasses.txt'